### ISSUE TITLE
NetBSD make

### ISSUE THREAD

**Issue by ng-0** [cheusov/mk-configure#15]
Is make in NetBSD-CURRENT base (still) usable with all parts of mk-configure?
pkgsrc currently requires devel/bmake for mk-configure.

**Comment by cheusov** [comment]
I assume NetBSD make from current should be good enough for mk-configure.
However I use bmake which is a snapshot from NetBSD source tree.
However, I'm not sure NetBSD make provides MAKE_VERSION variable.

**Comment by ng-0** [comment]
I just tried to build it with some if clauses for NetBSD but the check for bmake as it is in mk-configure 0.30.0 fails.

**Comment by ng-0** [comment]
current still has MAKE_VERSION appearing in line 1065 and 1066 in the source of main.c of make.

**Comment by cheusov** [comment]
Then, just try bmake as it is packed in Linux or pkgsrc. 20.02.2019, 15:24, "ng0" <notifications@github.com>:I just tried to build it with some if clauses for NetBSD but the check for bmake as it is in mk-configure 0.30.0 fails.—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by ng-0** [comment]
It would be good if this could be avoided at least on NetBSD, which is why I am asking.
The current pkgsrc package uses bmake from pkgsrc.
Is there another way you could check for the make on NetBSD to be compatible?

**Comment by cheusov** [comment]
I have no current right now. But that's how how NetBSD make differs from bmake. 0 cheusov>bmake -V MAKE_VERSION201505050 cheusov>make -V MAKE_VERSION0 cheusov>uname -srmNetBSD 8.99.12 amd640 cheusov> 21.02.2019, 00:41, "ng0" <notifications@github.com>:It would be good if this could be avoided at least on NetBSD, which is why I am asking.The current pkgsrc package uses bmake from pkgsrc.Is there another way you could check for the make on NetBSD to be compatible?—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by cheusov** [comment]
If you look inside mkcmake shell wrapper, you'll find variable MKC_BMAKE. It is settable by user and can be used in order to replace default bmake with our own version. Of course, this allows you to use NetBSD native make. In this case you also have to set MAKE_VERSION variable to something useful. Example of how it works for me on NetBSD-8.99.12

MKC_BMAKE=/usr/bin/make MAKE_VERSION=20180101 mkcmake all
